using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Numerics;
using Content.Client.Options.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._LT;
using Content.Shared.Movement.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.State;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._LT.VoreMenu;

[GenerateTypedNameReferences]
public sealed partial class VoreMenu : FancyWindow
{
    public List<BellyButton> gutbuttons = new List<BellyButton>();
    public Button? saveBtn;
    public VoreMenuEui Parent;
    public List<ContentTableRow> CTRs = new List<ContentTableRow>();
    public VoreMenu(VoreMenuEui parent)
    {
        Parent = parent;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Pred.OnButtonUp += PredOnOnButtonUp;
        Prey.OnButtonUp += PreyOnOnButtonUp;
    }



    public void HandleState(VoreMenuEuiState state)
    {
        gutbuttons.Clear();
        Bellies.Children.Clear();
        foreach (var belly in state.Tums)
        {
            BellyButton bellybuttonhahafunny = new BellyButton(belly.Id,new Button());
            bellybuttonhahafunny.button.Text = belly.Name;
            bellybuttonhahafunny.button.OnButtonUp += BellySelected;
            Bellies.AddChild(bellybuttonhahafunny.button);
            gutbuttons.Add(bellybuttonhahafunny);
        }

        Button newgut = new Button();
        newgut.Text = "New";
        newgut.OnButtonUp += NewgutOnOnButtonUp;
        Bellies.AddChild(newgut);

        if (state.CurrentTum is not null)
        {
            BellyConfig.Children.Clear();
            BoxContainer namecontainer = new BoxContainer();
            namecontainer.Orientation = BoxContainer.LayoutOrientation.Horizontal;
            namecontainer.HorizontalExpand = true;
            Label nameLa = new Label();
            nameLa.Text = "Name:";
            LineEdit nameLE = new LineEdit();
            nameLE.Text = state.CurrentTum.Name;
            nameLE.OnTextChanged += NameLEOnOnTextChanged;
            nameLE.MinWidth = 100;
            namecontainer.AddChild(nameLa);
            namecontainer.AddChild(nameLE);
            BellyConfig.AddChild(namecontainer);

            BoxContainer desccontainer = new BoxContainer();
            desccontainer.Orientation = BoxContainer.LayoutOrientation.Horizontal;
            desccontainer.HorizontalExpand = true;
            Label DescLa = new Label();
            DescLa.Text = "Description:";

            LineEdit descTE = new LineEdit();
            descTE.Text = state.CurrentTum.InnerDescription;
            descTE.OnTextChanged += DescTEOnOnTextChanged;
            descTE.MinWidth = 200;
            descTE.Editable = true;
            desccontainer.AddChild(DescLa);
            desccontainer.AddChild(descTE);
            BellyConfig.AddChild(desccontainer);

            BoxContainer DigestModeContainer = new BoxContainer();
            Label DMLabel = new Label();
            DMLabel.Text = "Belly mode:";

            OptionButton DMODD = new OptionButton();

            foreach (var modetype in Enum.GetValues<BellyDigestMode>())
            {
                DMODD.AddItem(modetype.ToString(), (byte)modetype);
            }

            DMODD.SelectId((byte)state.CurrentTum.Mode);
            DMODD.OnItemSelected += args =>
            {
                DMODD.SelectId(args.Id);
                SelectDM(args.Id.ToString());
            };
            DigestModeContainer.AddChild(DMLabel);
            DigestModeContainer.AddChild(DMODD);
            BellyConfig.AddChild(DigestModeContainer);

            BoxContainer ingestdesccontainer = new BoxContainer();
            ingestdesccontainer.Orientation = BoxContainer.LayoutOrientation.Horizontal;
            ingestdesccontainer.HorizontalExpand = true;
            Label ingestdescLa = new Label();
            ingestdescLa.Text = "Ingest verb:";
            LineEdit ingestdescLE = new LineEdit();
            ingestdescLE.Text = state.CurrentTum.IngestDesc;
            ingestdescLE.OnTextChanged += IngestdescLEOnOnTextChanged;
            ingestdescLE.MinWidth = 200;
            ingestdesccontainer.AddChild(ingestdescLa);
            ingestdesccontainer.AddChild(ingestdescLE);
            BellyConfig.AddChild(ingestdesccontainer);

            BoxContainer expelldesccontainer = new BoxContainer();
            expelldesccontainer.Orientation = BoxContainer.LayoutOrientation.Horizontal;
            expelldesccontainer.HorizontalExpand = true;
            Label expelldescLa = new Label();
            expelldescLa.Text = "Expell verb:";
            LineEdit expelldescLE = new LineEdit();
            expelldescLE.Text = state.CurrentTum.ExpellDesc;
            expelldescLE.OnTextChanged += ExpelldescLEOnOnTextChanged;
            expelldescLE.MinWidth = 200;
            expelldesccontainer.AddChild(expelldescLa);
            expelldesccontainer.AddChild(expelldescLE);
            BellyConfig.AddChild(expelldesccontainer);

            BoxContainer DPreddesccontainer = new BoxContainer();
            DPreddesccontainer.Orientation = BoxContainer.LayoutOrientation.Horizontal;
            DPreddesccontainer.HorizontalExpand = true;
            Label DPreddescLa = new Label();
            DPreddescLa.Text = "Digest (for you) description:";
            LineEdit DPreddescLE = new LineEdit();
            DPreddescLE.Text = state.CurrentTum.DigestDescPred;
            DPreddescLE.OnTextChanged += DPreddescLEOnOnTextChanged;
            DPreddescLE.MinWidth = 200;
            DPreddesccontainer.AddChild(DPreddescLa);
            DPreddesccontainer.AddChild(DPreddescLE);
            BellyConfig.AddChild(DPreddesccontainer);

            BoxContainer DPreydesccontainer = new BoxContainer();
            DPreydesccontainer.Orientation = BoxContainer.LayoutOrientation.Horizontal;
            DPreydesccontainer.HorizontalExpand = true;
            Label DPreydescLa = new Label();
            DPreydescLa.Text = "Digest (for prey) description:";
            LineEdit DPreydescLE = new LineEdit();
            DPreydescLE.Text = state.CurrentTum.DigestDescPrey;
            DPreydescLE.OnTextChanged += DPreydescLEOnOnTextChanged;
            DPreydescLE.MinWidth = 200;
            DPreydesccontainer.AddChild(DPreydescLa);
            DPreydesccontainer.AddChild(DPreydescLE);
            BellyConfig.AddChild(DPreydesccontainer);

            BoxContainer SaveBtnContainer = new BoxContainer();
            Button saveBtn = new Button();
            saveBtn.Text = "Save to slot";
            saveBtn.Disabled = true;
            saveBtn.OnButtonUp += SaveBtnOnOnButtonUp;
            SaveBtnContainer.AddChild(saveBtn);
            BellyConfig.AddChild(SaveBtnContainer);
            this.saveBtn = saveBtn;

            BoxContainer ContentsLabelContainer = new BoxContainer();
            Label ContentsLa = new Label();
            ContentsLa.Text = "Contents";
            ContentsLabelContainer.AddChild(ContentsLa);
            BellyConfig.AddChild(ContentsLabelContainer);

            BoxContainer ContentsSCContainer = new BoxContainer();
            CTRs.Clear();
            foreach (KeyValuePair<string,string> kvp in state.Contentsgsp)
            {

                BoxContainer ContentsTableContainer = new BoxContainer();
                var row = new ContentTableRow(kvp);
                ContentsTableContainer.AddChild(row.La);
                ContentsTableContainer.AddChild(row.EjectBtn);
                row.EjectBtn.OnButtonUp += EjectBtnOnOnButtonUp;
                CTRs.Add(row);
                ContentsSCContainer.AddChild(ContentsTableContainer);

            }
            BellyConfig.AddChild(ContentsSCContainer);

        }

        if (state.predpref)
        {
            Pred.Text = "Pred pref: ENABLED";
        }
        else
        {
            Pred.Text = "Pred pref: DISABLED";
        }

        if (state.preypref)
        {
            Prey.Text = "Prey pref: ENABLED";
        }
        else
        {
            Prey.Text = "Prey pref: DISABLED";
        }

    }

    private void EjectBtnOnOnButtonUp(BaseButton.ButtonEventArgs obj)
    {
        string[] split = obj.Button.Name!.Split(";");
        var ctr = CTRs.FirstOrDefault(instance => instance.id == split[1]);
        if (ctr != null)
        {
            Parent.Eject(ctr.id);
        }
    }

    private void DPreydescLEOnOnTextChanged(LineEdit.LineEditEventArgs obj)
    {
        Parent.EditDPreyDesc(obj.Text);
        saveBtn!.Disabled = false;
    }

    private void DPreddescLEOnOnTextChanged(LineEdit.LineEditEventArgs obj)
    {
        Parent.EditDPredDesc(obj.Text);
        saveBtn!.Disabled = false;

    }

    private void ExpelldescLEOnOnTextChanged(LineEdit.LineEditEventArgs obj)
    {
        Parent.EditExpellDesc(obj.Text);
        saveBtn!.Disabled = false;
    }

    private void IngestdescLEOnOnTextChanged(LineEdit.LineEditEventArgs obj)
    {
        Parent.EditIngestDesc(obj.Text);
        saveBtn!.Disabled = false;
    }

    private void NewgutOnOnButtonUp(BaseButton.ButtonEventArgs obj)
    {
        Parent.NewGut();
    }

    private void SaveBtnOnOnButtonUp(BaseButton.ButtonEventArgs obj)
    {
        Parent.SaveToSlot();
        saveBtn!.Disabled = true;
    }

    private void DescTEOnOnTextChanged(LineEdit.LineEditEventArgs obj)
    {
        Parent.EditDescription(obj.Text);
        saveBtn!.Disabled = false;

    }

    private void NameLEOnOnTextChanged(LineEdit.LineEditEventArgs obj)
    {
        Parent.EditName(obj.Text);
        saveBtn!.Disabled = false;
    }

    private void BellySelected(BaseButton.ButtonEventArgs obj)
    {
        BellyButton bb = gutbuttons.Find(instance => instance.button.Equals(obj.Button))!;
        Parent.SelectBelly(bb.reference);
    }

    void SelectDM(string notbyte)
    {
        Parent.SelectDM(notbyte);
        saveBtn!.Disabled = false;
    }

    private void PreyOnOnButtonUp(BaseButton.ButtonEventArgs obj)
    {
        Parent.TogglePreyPref();
    }

    private void PredOnOnButtonUp(BaseButton.ButtonEventArgs obj)
    {
        Parent.TogglePredPref();
    }




}
